#ifndef ERRORS
#define ERRORS

enum
{
    SOURCEFILE_NOT_SELECTED = -99,
    DESTINATIONFILE_NOT_SELECTED,
    OPERATION_UNSUCCESS = -1,
    SUCCESS,
    OPERATION_CANCELLED
};

#endif // ERRORS

